---
#
#- name: Set facts
#  set_fact:
#    cp_vip: {{ private_subnet | ansible.netcommon.ipaddr('-1') }}

- import_playbook: rhel.yaml
- import_playbook: ubuntu.yaml
- name: Download bmctl
  community.google.gc_storage:
    bucket: anthos-baremetal-release/bmctl/"{{ bmctl_version }}"/linux-amd64/
    object: bmctl
    dest: $HOME/bootstrap/bmctl
    mode: get
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: $HOME/bootstrap/gcp_keys/bmctl.json
- name: Change bmctl permissions
  ansible.builtin.file:
    path: $HOME/bootstrap/bmctl
    mode: '0755'
- name: Create cluster config
  ansible.builtin.shell:
    chdir: $HOME/bootstrap
    cmd: $HOME/bootstrap/bmctl create config -c {{ cluster_name }} --enable-apis --create-service-accounts --project-id={{ gcp_project_id }}
    creates: bmctl-workspace/{{ cluster_name }}/{{ cluster_name }}.yaml
