- name: Set facts cp_vip
  set_fact:
    cp_vip: "{{ private_subnet | ansible.netcommon.nthhost('-2')}}"
    ingress_vip: "{{ private_subnet | ansible.netcommon.nthhost('-3')}}"
    lb_range_start: "{{ private_subnet | ansible.netcommon.nthhost('-14')}}"

- name: bmctl key
  set_fact:
    bmctl_key: "{{ lookup('file', '{{ home_path }}/bootstrap/gcp_keys/bmctl.json')\
      \ | from_json }}"

- import_tasks: rhel.yaml
- import_tasks: ubuntu.yaml

- name: Download bmctl
  ansible.builtin.shell:
    chdir: '{{ home_path }}/bootstrap'
    cmd: gcloud auth activate-service-account --key-file={{ home_path }}/bootstrap/gcp_keys/gcr.json
      && gsutil cp gs://anthos-baremetal-release/bmctl/{{ bmctl_version }}/linux-amd64/bmctl
      .
    creates: '{{ home_path }}/bootstrap/bmctl'

- name: Change bmctl permissions
  ansible.builtin.file:
    path: '{{ home_path }}/bootstrap/bmctl'
    mode: '0755'
- name: Create cluster config
  ansible.builtin.shell:
    chdir: '{{ home_path }}/bootstrap'
    cmd: '{{ home_path }}/bootstrap/bmctl create config -c {{ cluster_name }} --project-id={{
      gcp_project_id }}'
    creates: '{{ home_path }}/bootstrap/bmctl-workspace/{{ cluster_name }}/{{ cluster_name
      }}.yaml'
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: '{{ home_path }}/bootstrap/gcp_keys/bmctl.json'

- name: Replace cluster config file
  template:
    src: bmctl.conf.j2
    dest: '{{ home_path }}/bootstrap/bmctl-workspace/{{ cluster_name }}/{{ cluster_name
      }}.yaml'

# task to create
- name: Create cluster
  ansible.builtin.shell:
    chdir: '{{ home_path }}/bootstrap'
    cmd: '{{ home_path }}/bootstrap/bmctl create cluster -c {{ cluster_name }} &>
      {{ home_path }}/bootstrap/cluster_create.log'
    creates: '{{ home_path }}/bootstrap/bmctl-workspace/{{ cluster_name }}/{{ cluster_name
      }}-kubeconfig'
  environment:
    GOOGLE_APPLICATION_CREDENTIALS: '{{ home_path }}/bootstrap/gcp_keys/bmctl.json'

- name: Create .kube directory
  ansible.builtin.file:
    path: '{{ home_path }}/.kube'
    state: directory
    mode: '0755'
    group: '{{ username }}'
    owner: '{{ username }}'

- name: Copy kubeconfig to ~/.kube
  ansible.builtin.copy:
    src: '{{ home_path }}/bootstrap/bmctl-workspace/{{ cluster_name }}/{{ cluster_name
      }}-kubeconfig'
    dest: '{{ home_path }}/.kube/config'
    owner: '{{ username }}'
    group: '{{ username }}'
    mode: '0644'
