---
- name: Install Google Cloud SDK pre-reqs
  ansible.builtin.apt:
    update_cache: yes
    pkg:
    - apt-transport-https
    - ca-certificates
    - gnupg
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Add Google Cloud Apt signing key to a specific keyring file
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    keyring: /usr/share/keyrings/cloud.google.gpg
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Add Google Cloud repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: Install Google Cloud SDK
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
    pkg:
    - google-cloud-sdk
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'