# TODO: This needs to be fixed!
- name: Set Equinix Metal metadata as fact
  ansible.builtin.set_fact:
    eqm_metadata: "{{ lookup('ansible.builtin.url', 'https://metadata.platformequinix.com/metadata') | from_json }}"
    cacheable: yes

# TODO: This needs to be fixed!
- name: Set private network subnet
  ansible.builtin.set_fact: 
    private_net: "{{ ansible_fact.eqm_metadata.network.addresses | json_query('[?!public].network')[0] }}/{{ ansible_fact.eqm_metadata.network.addresses | json_query('[?!public].cidr') }}"
    cacheable: yes
