- name: Set Equinix Metal metadata as a fact
  ansible.builtin.set_fact:
    eqm_metadata: "{{ lookup('ansible.builtin.url', 'https://metadata.platformequinix.com/metadata') | ansible.builtin.from_json }}"
- name: Set private network id as a fact
  ansible.builtin.set_fact:
    private_network_id: "{{ eqm_metadata.network.addresses | json_query('[?!public].network | [0]') }}"
- name: Set private network cidr as a fact
  ansible.builtin.set_fact:
    private_network_cidr: "{{ eqm_metadata.network.addresses | json_query('[?!public].cidr | [0]') }}"
- name: Set private network as a fact
  ansible.builtin.set_fact:
    private_network: "{{ private_network_id }}/{{ private_network_cidr }}" 
- name: Set first private IP as a fact
  ansible.builtin.set_fact:
    first_private_ip: "{{ private_network | ansible.utils.nthhost('1') }}"