# TODO: This needs to be fixed!
- name: Set Equinix Metal metadata as a fact
  ansible.builtin.set_fact:
    eqm_metadata: "{{ lookup('ansible.builtin.url', 'https://metadata.platformequinix.com/metadata') | ansible.builtin.from_json }}"

# TODO: This needs to be fixed!
- name: Set first private IP as a fact
  ansible.builtin.set_fact: 
    first_private_ip: "{{ eqm_metadata.network.addresses | ansible.builtin.json_query('[?!public].network')[0] | ansible.utils.nthhost('1') }}"