---
- name: Stop and disable apparmor service
  ansible.builtin.service:
    name: apparmor
    state: stopped
    enabled: False

- name: Disable UFW
  community.general.ufw:
    state: disabled

- name: Install Python3 jmespath Module
  ansible.builtin.apt:
    update_cache: yes
    pkg:
    - python3-jmespath
