---
- name: Set first private IP as a fact
  ansible.builtin.set_fact:
    second_private_ip: "{{ hostvars[inventory_hostname]['ansible_facts']['private_network'] | ansible.utils.nthhost('2') }}"
    cacheable: yes

- name: Replace first private ip with second private ip in /etc/network/interfaces
  ansible.builtin.replace:
    path: /etc/network/interfaces
    regexp: first_private_ip
    replace: second_private_ip
  notify: Restart networking
